CREATE TABLE IF NOT EXISTS users (
    userid CHAR(36) PRIMARY KEY,
    user_name VARCHAR(255) UNIQUE NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('ADMINISTRATOR', 'SUPERADMIN', 'CLIENT') NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status ENUM('ACTIVATED', 'DEACTIVATED') DEFAULT 'ACTIVATED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);